import assert from 'node:assert/strict';
import fs from 'node:fs';

const game = fs.readFileSync('game.js','utf8');
const html = fs.readFileSync('index.html','utf8');
const css = fs.readFileSync('styles.css','utf8');
const server = fs.readFileSync('server.mjs','utf8');
const runtimeConfig = fs.readFileSync('runtime-config.js','utf8');

assert.match(game,/new THREE\.WebGLRenderer/,'real WebGL renderer required');
assert.match(game,/__ROOTAGENT_PLAYTEST__/,'RootAgent runtime hook required');
assert.match(game,/journey:/,'journey telemetry required');
assert.match(game,/outcome:/,'outcome telemetry required');
assert.match(game,/feel:/,'feel telemetry required');
for (const tactic of ['CHASE','STRAFE','RETREAT','ATTACK','GUARD']) assert.match(game,new RegExp("'" + tactic + "'"));
assert.match(game,/https:\/\/api\.typesafe\.ai\/v1\/systemone/,'JEV endpoint required');
assert.match(server,/authorization:'Bearer '\+key/,'server-side bearer forwarding required');
assert.match(server,/UNBOUNDED_TACTICS/,'server must reject unbounded tactic sets');
assert.match(game,/state\.sessionKey/,'Pages session-only credential path required');
assert.match(game,/URLSearchParams\(location\.search\).*jev_proxy/,'local proxy must require an explicit URL capability flag');
assert.match(server,/runtime-config\.js/,'local server must explicitly enable proxy mode');
assert.match(runtimeConfig,/__AEGIS_LOCAL_PROXY__ = false/,'static Pages must disable local proxy mode');
assert.doesNotMatch(game,/localStorage|sessionStorage/,'credential must not persist in browser storage');
assert.doesNotMatch(game,/apikey_[A-Za-z0-9_]+/,'real key must not be embedded');
assert.doesNotMatch(html,/apikey_[A-Za-z0-9_]+/,'real key must not be embedded in HTML');
assert.doesNotMatch(server,/apikey_[A-Za-z0-9_]+/,'real key must not be embedded in server');
assert.match(html,/WASD/); assert.match(html,/SPACE/); assert.match(html,/SHIFT/);
assert.match(css,/backdrop-filter/); assert.ok(css.length > 3000,'polished UI stylesheet expected');
for (const id of ['ac-0e3cb03b14e8','ac-dc1e758d370b','ac-5512e204c4de']) assert.match(game,new RegExp(id));
console.log('ok - AEGIS DRIFT WebGL/JEV/security/RootAgent contract smoke checks pass');
